### ISSUE TITLE
 Hi Team, Kong unirest , post method I am calling every request Unirest.reset(). connectionTimeout(600000). enableCookieManagement(false): Unirest.post("http://127.0.0.1").asJson();. After continues different api call I'm getting socket exception : socket closed and some time I got illicalstateexception connection pool shutdown  Balaji Arumugam 17:31 Kindly correct me. If I am doing wrong configuration

### ISSUE THREAD

**Issue by Barumugam3** [Kong/unirest-java#422] opened 2021-12-24 13:41 UTC
**Describe the bug**

**To Reproduce**
1. Provide as much of a code sample as possible. Unirest is pretty small so it you should be able to mostly copy-paste into the issue
1. do **NOT** paste authentication or client keys into the issue
1. provide full stack traces if possible

**Expected behavior**

**Screenshots**

**Environmental Data:**
 - Java Version
 - Version [e.g. 3.3.03]

**Additional context**

**Comment by ryber** [comment] 2021-12-24 13:59
You shouldn't be resetting the connection over and over again, the configuration on an instance should be fairly static. Any time you call reset() you are going to end up closing the existing pool

**Comment by ryber** [comment] 2021-12-24 14:00
duplicate of https://github.com/Kong/unirest-java/issues/127

**Closed** 2022-01-06 13:28 UTC
