### ISSUE TITLE
Synchronization Issue with as*Async methods (ThreadStateException)

### ISSUE THREAD

**Issue by bennylut** [Kong/unirest-java#143] opened 2016-04-17 11:15 UTC
Hello, 
There is a synchronization issue in the method `com.mashape.unirest.http.HttpClientHelper.requestAsync`. 
To explain the problem I will post the relevant method code here: 

``` java
public static <T> Future<HttpResponse<T>> requestAsync(HttpRequest request, final Class<T> responseClass, Callback<T> callback) {
        HttpUriRequest requestObj = prepareRequest(request, true);

        CloseableHttpAsyncClient asyncHttpClient = ClientFactory.getAsyncHttpClient();

        if (!asyncHttpClient.isRunning()) { //ENTER CS
            asyncHttpClient.start();
            AsyncIdleConnectionMonitorThread asyncIdleConnectionMonitorThread = (AsyncIdleConnectionMonitorThread) Options.getOption(Option.ASYNC_MONITOR);
            asyncIdleConnectionMonitorThread.start(); // <-- this line throws ThreadStateException
        }
//... rest of the code
}
```

The problem is that if several threads attempt to perform requests with as*Async operations at the same time then it can happen that two threads will enter `if` in the line marked with `ENTER_CS` on the same time  start the `asyncHttpClient` and then the `asyncIdleConnectionMonitorThread`. Since the `asyncIdleConnectionMonitorThread`'s `start` method will be called twice -  the second  time will throw ThreadStateException (starting a thread that is already started).

Here is a simple program that reproduce the bug

``` java
public static void main(String[] args)  {
        int threads = 8;
        CountDownLatch letch = new CountDownLatch(1);
        for (int i = 0; i < threads; i++) {
            new Thread(() -> {
                try {
                    letch.await();
                    Unirest.get("http://www.google.com").asStringAsync().get();
                } catch (InterruptedException | ExecutionException  ex) {
                    Logger.getLogger(Bug.class.getName()).log(Level.SEVERE, null, ex);
                }

            }).start();
        }

        letch.countDown();
    }
```

**Comment by dmitrymurashenkov** [comment] 2016-08-12 19:24
Want to upvote this issue. I've ran into same problem when using Unirest for simple load testing and performing several requests in parallel.

However in my simple scenario it seems that the problem can only happen during first request when Unirest is not initialized (didn't look into details).

I've ran my tests with @bennylut branch and can confim that it works! However I didn't perform a code review. 

At first I wanted to submit a unit test for this, but since my test can only reproduce the problem when it is the first test run in the JVM I think it is not valuable enough.

**Comment by berupp** [comment] 2016-08-23 18:54
Hitting this as well, using the 'warm-up' workaround for it for now.

**Comment by JamieSinn** [comment] 2017-10-21 16:03
Any update on this? This is a serious breaker for me. Debating using @bennylut's branch if it's still stable.

**Comment by berupp** [comment] 2017-10-22 00:18
I must advice against using unirest. While @bennylut workaround fixes this issue, there is another serious issue in one of its dependencies, which we discovered lately and haven't been able to resolve. 

This project is not maintained anymore. I'd advice to use something else, or fork it with the expectation to maintain it yourself.

**Comment by djKianoosh** [comment] 2017-11-27 21:56
:(

**Comment by djKianoosh** [comment] 2017-11-27 21:58
Here's a fork: https://github.com/josueeduardo/rest-client

**Comment by ryber** [comment] 2019-03-07 12:43
This should be fixed in Unirest 2 now

**Closed by ryber** 2019-03-07 12:43 UTC
