### ISSUE TITLE
Thousands of threads?

### ISSUE THREAD

**Issue by tommytusj** [Kong/unirest-java#140] opened 2016-03-26 13:56 UTC
Connected to Tomcat with JConsole and see thousands and thousands of threads like this. Why is that?

Stack Trace
   java.lang.Object.$$YJP$$wait line: not available [native method]
   java.lang.Object.wait line: not available 
   com.mashape.unirest.http.utils.SyncIdleConnectionMonitorThread.run line: 22 

We are using Unirest alot in one of the applications running there. Does every Unirest call spawn threads?

**Comment by tommytusj** [comment] 2016-04-01 11:05
I've found out why. Every time you use Unirest.setTimeout() there is a new thread created. Design flaw?

**Comment by yogeshnachnani** [comment] 2016-05-03 06:05
I've just started looking at this codebase, and I think that the timeouts are supposed to be configured just once. They are part of a static Options context

**Comment by ericblue** [comment] 2017-02-14 21:11
Hi,

What's the status of this issue?  And of https://github.com/Mashape/unirest-java/issues/148?  

We have a somewhat high-use queue and processor that uses uniREST for a core library.  After a bit of debugging it seems thousands of threads are being allocated by UniRest.  And, AFAIK there is absolutely no way to control this.  Setting concurrency options also appears to have no affect (setting to 1 for max size, and 1 for the route does nothing).

**Comment by ericblue** [comment] 2017-02-14 21:49
And, a little additional context for anybody else reading this (gleaned from #148).  My temporary 'fix'
was to stop calling setProxy multiple times.  Apparently, anything that calls options.refresh() internally (setProxy() or setTimeouts()).  Will cause additional threads to be created.. and more importantly these are not controllable and will grow out of control.

I've enjoyed using UniRest.  It's super simple and intuitive.  But, I'd agree with the other comments that there is a design flaw here.  I do get the advantage of static methods, but there has to be better way to encapsulate and keep state.  Especially since if this library is wrapped inside another object, interacting with this in an OO way will produce unexpected and potentially dangerous results.

Finally, I hope there is a plan to address.  The age of this and other tickets are quite old and I see no comments from the maintainers.  Maybe worth a follow-up with support at Mashape.

**Comment by tommytusj** [comment] 2017-02-14 21:55
We're using https://github.com/hgoebl/DavidWebb because of this issue. Maybe it's to lightweight for your use? but it works perfectly for us

**Comment by ericblue** [comment] 2017-02-15 02:56
Thanks @tommytusj.  I'll check that out.  I was also looking at OkHttp.

I've 'fixed' the issue for now and just moved setProxy elsewhere in the code so it isn't abstracted and called more than once.  I'll be honest... this issue is pretty irritating.  One should not expect multiple threads to be created on simple, static methods for setting proxies and timeouts.  AND, at a minimum, the should at least be called out in the docs immediately... as in, do NOT call these methods more than once.  I have no problem reading code or browsing through tickets, but it shouldn't have to come to this.  Sorry </rant>.

**Comment by RomeLeader** [comment] 2018-03-20 15:17
I also switched my project to OKHTTP after grappling with this issue for a while and having no idea why until I found this issue. The issue is over two years old, and effectively makes efforts to run a polling service with multiple threads (my case) impossible. Really needs a fix or documentation to the effect.

**Comment by enantiomer2000** [comment] 2018-04-18 23:09
Taking out Unirest.setTimeout() from my web service calls fixed the problem for me. I still consider this a bug though.

**Comment by ryber** [comment] 2019-03-06 13:17
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

**Closed by ryber** 2019-03-06 13:17 UTC
