### ISSUE TITLE
IllegalThreadStateException in HttpClientHelper.requestAsync (HttpClientHelper.java:100)

### ISSUE THREAD

**Issue by jokraehe** [Kong/unirest-java#92] opened 2015-05-19 12:09 UTC
We're getting this error when calling requestAsync parallel during performance testing our application with gatling.

java.lang.IllegalThreadStateException: null
    at java.lang.Thread.start(Thread.java:705) ~[na:1.8.0_40]
    at com.mashape.unirest.http.HttpClientHelper.requestAsync(HttpClientHelper.java:100) ~[unirest-java-1.4.5.jar:na]
    at com.mashape.unirest.request.BaseRequest.asStringAsync(BaseRequest.java:64) ~[unirest-java-1.4.5.jar:na]

**Comment by varra4u** [comment] 2015-05-26 19:22
Hi @jokraehe 

We are not able to reproduce the issue!! Could you please share us the test case or scenario you have used to get this error!!

**Comment by cookingfox** [comment] 2015-06-22 09:13
I just ran into the same issue when performing multiple async call concurrently.

I've created a gist which demonstrates the behaviour: https://gist.github.com/cookingfox/40c65a779bf49fb2d936

Of the two calls in the example, one will fail with the following error:

```java
java.lang.IllegalThreadStateException
	at java.lang.Thread.start(Thread.java:705)
	at com.mashape.unirest.http.HttpClientHelper.requestAsync(HttpClientHelper.java:100)
	at com.mashape.unirest.request.BaseRequest.asStringAsync(BaseRequest.java:64)
	at Main$1.run(Main.java:27)
	at Main$2.run(Main.java:73)
	at java.lang.Thread.run(Thread.java:745)
```

I'm using Unirest version 1.4.5.

**Comment by cookingfox** [comment] 2015-06-22 09:15
@jokraehe Did you fix your issue eventually?

**Comment by MrGraversen** [comment] 2015-12-02 12:31
I just ran into the same issue when launching many "asAsyncJson" requests concurrently.

Using OS X El Capitan.

**Comment by MrGraversen** [comment] 2015-12-02 12:46
OK — I believe problem lies here: https://github.com/Mashape/unirest-java/blob/master/src/main/java/com/mashape/unirest/http/HttpClientHelper.java#L96

If multiple threads invoke, for example, `asAsyncJson`, thread two thread might still encounter `false` for the condition in the if-statement because thread one has not returned from `asyncIdleConnectionMonitorThread.start();` (which causes the exception).

The solution for me was to "warm up" Unirest with one single request. Then, it appears, the throughput isn't limited.

**Comment by djKianoosh** [comment] 2016-02-18 13:23
@MrGraversen what do you mean by "warm up"?

**Comment by MrGraversen** [comment] 2016-02-24 09:15
@djKianoosh I mean letting a single request fire before anything else. I just `GET` request `localhost` when my application starts up, then when my threads start submitting API calls at rapid pace, this problem does not occur.

**Comment by paulrene** [comment] 2016-03-09 09:38
Doing the "warm up" is ok for a temporary workaround, but this should not be the permanent solution. Is there any plans for a proper fix for this problem?

**Comment by djKianoosh** [comment] 2016-03-09 14:17
I agree. I hadn't seen it until just recently during some additional testing. It's not easily reproducible however, so I'm not sure how to best devise a unit test for this here.

**Comment by gholol** [comment] 2016-06-02 07:55
Any updates?

**Comment by dmitrymurashenkov** [comment] 2016-08-12 19:45
Also duplicated by #143 (fix available there)

**Comment by ryber** [comment] 2019-03-06 13:39
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

**Closed by ryber** 2019-03-06 13:39 UTC
