### ISSUE TITLE
Failing to upload file

### ISSUE THREAD

**Issue by ygalblum** [Kong/unirest-java#61] opened 2014-12-30 12:36 UTC
I'm following your example in CamFind service on Mashape.

When using a remote URL everything works fine. But when trying to upload a file I get the following exception:
SEVERE: Failed to execute request
com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
    at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:145)
    at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
    at com.jungo.image2hashtag.CamFind.processFile(CamFind.java:79)
    at com.jungo.image2hashtag.Main.main(Main.java:25)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
    at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:102)
    at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:141)
    ... 3 more
Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
    at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
    at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:93)
    ... 4 more
Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
    at org.json.JSONArray.<init>(JSONArray.java:105)
    at org.json.JSONArray.<init>(JSONArray.java:144)
    at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
    ... 5 more

If instead, I break all function calls to separate lines, the requests goes to the server and returns with an error stating the the "image" field is empty.

It seems there is a problem with the "field" method when supplying a "File", or the documentation is not up to date.

BTW I had similar issues with the JS version, where in a newer version the API for attaching files was changes from providing a ReadStream to providing the file path.

BR Ygal

**Comment by thefosk** [comment] 2015-01-20 19:18
I think this is caused by the fact that the server is not responding with a proper JSON response. Can you try to invoke the request calling `.asString()` instead of `.asJson()` and paste the output here?

**Comment by beemi** [comment] 2016-02-04 15:37
Yes , if any invalid data in Request queryString, it just throws the above errors, i did get the same exception with the invalid queryString, but not the Json format

**Comment by ryber** [comment] 2019-03-06 14:15
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

**Closed by ryber** 2019-03-06 14:15 UTC
