### ISSUE TITLE
setHttpClient() needs to be called before every request?

### ISSUE THREAD

**Issue by WiteCastle** [Kong/unirest-java#195] opened 2017-02-02 17:22 UTC
I have a custom httpClient set up like so:

```java
SSLContext sslContext = SSLContexts.custom().loadKeyMaterial(keystore, keystorePass).build();
SSLConnectionSocketFactory sslsf = new SSLConnectionSocketFactory( 
        sslContext, new String[] {"TLSv1.2"}, null,  
        SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
CloseableHttpClient httpClient = HttpsClients.custom()
        .setHostnameVerifier(SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER)   
        .setSSLSocketFactory(sslsf)
        .build();

Unirest.setHttpClient(httpClient);
```

This is called before I make any REST calls. However, I have to set the httpClient in every subsequent call. For example if I call this method in a later part of my code after I set the httpClient I still have to set it with a method that returns the httpClient made above (getHttpClient).

```java
public void makeRestCall(){
    Unirest.setHttpClient(getHttpClient());
    HttpResponse<JsonNode> json = Unirest.get("https://example.net")
                               .queryString("start", 0)
                               .queryString("limit", 300)
                               .asJson();
}
```

I get a bad_certificate error if I don't reset the HttpClient explicitly. Should the httpClient need to be set only once?

**Comment by ricardo-kagawa** [comment] 2017-03-18 02:40
Well, I have just started using it, and ran into a similar problem. It seems that you have to set it last in your configuration, as far as I can tell from the source code. For instance, if you configure an object mapper after setting the custom client, the client setting will be reset and you have to set it again. I have done that in JUnit, so I can confirm this workaround.

For the people interested in fixing this, the problem is in the Options.reload() method that gets called after setting each configuration option. It will recreate the default client without regards to the custom setting. It seems there already is a variable in that class to track whether there is a custom client setting, which is not used in this context (but could very well be).

**Comment by ryber** [comment] 2019-03-06 00:42
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

**Closed by ryber** 2019-03-06 00:42 UTC
Labels: V2 Supported
